[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyovobj"
version = "1.5.0"
authors = [
  { name="good9527", email="good9527@users.noreply.github.com" },
]
description = "Native Ovital (.ovobj) Vector Decoding and Multi-Format GIS/CAD Conversion Toolkit"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: GIS",
]
dependencies = [
    "geopandas>=0.14.0",
    "shapely>=2.0.0",
    "pyproj>=3.6.0",
    "pandas>=2.0.0",
    "ezdxf>=1.4.0",
    "openpyxl>=3.1.0",
]

[project.scripts]
ovobj-converter = "pyovobj.cli:main"
